"""Contract/evidence-driven phase gate primitives."""

from umbrella.contracts.compiler import ContractCompiler
from umbrella.contracts.decision import PhaseDecisionEngine, decide_phase_transition
from umbrella.contracts.evidence import EvidenceResolver, build_workspace_context
from umbrella.contracts.hashing import diff_hash, hash_value, workspace_hash
from umbrella.contracts.harness_profiles import (
    HarnessProfile,
    all_harness_profiles,
    build_harness_contract_payload,
    known_harness_profile_ids,
    probe_required_capability_ids,
)
from umbrella.contracts.models import (
    CURRENT_CONTRACT_VERSION,
    Actor,
    ArtifactDigest,
    CompletedClaim,
    CompletionContract,
    ContractBundle,
    ContractEnvelope,
    ContractIssue,
    EvidenceRef,
    PhaseDecision,
    PlanIR,
    ProofAntiGamingSpec,
    ProofExecutionSpec,
    ProofOracleSpec,
    ProofScopeSpec,
    ProofSpec,
    ResearchSummaryContract,
    ReviewContract,
    ReviewIssue,
    SubtaskIR,
    TaskRiskProfile,
    UmbrellaAttestation,
    VerificationReportRef,
    WorkspaceContext,
    json_ready,
)
from umbrella.contracts.plan_ir import canonicalize_phase_plan, compile_phase_plan
from umbrella.contracts.policy_input import to_policy_input
from umbrella.contracts.layout_policy import validate_plan_layout_policy
from umbrella.contracts.validators import (
    ContractValidator,
    validate_completion_contract,
    validate_completion_materialization,
    validate_done_subtasks_materialized,
    validate_envelope,
    validate_proof_spec,
    validate_review_contract,
    validate_verification_report_ref,
)

__all__ = [
    "CURRENT_CONTRACT_VERSION",
    "Actor",
    "ArtifactDigest",
    "CompletedClaim",
    "CompletionContract",
    "ContractBundle",
    "ContractCompiler",
    "ContractEnvelope",
    "ContractIssue",
    "ContractValidator",
    "EvidenceRef",
    "EvidenceResolver",
    "HarnessProfile",
    "PhaseDecision",
    "PhaseDecisionEngine",
    "PlanIR",
    "ProofAntiGamingSpec",
    "ProofExecutionSpec",
    "ProofOracleSpec",
    "ProofScopeSpec",
    "ProofSpec",
    "ResearchSummaryContract",
    "ReviewContract",
    "ReviewIssue",
    "SubtaskIR",
    "TaskRiskProfile",
    "UmbrellaAttestation",
    "VerificationReportRef",
    "WorkspaceContext",
    "build_workspace_context",
    "all_harness_profiles",
    "build_harness_contract_payload",
    "canonicalize_phase_plan",
    "compile_phase_plan",
    "decide_phase_transition",
    "diff_hash",
    "hash_value",
    "json_ready",
    "known_harness_profile_ids",
    "probe_required_capability_ids",
    "to_policy_input",
    "validate_completion_contract",
    "validate_completion_materialization",
    "validate_done_subtasks_materialized",
    "validate_envelope",
    "validate_proof_spec",
    "validate_review_contract",
    "validate_verification_report_ref",
    "validate_plan_layout_policy",
    "workspace_hash",
]

